// Every user-facing text of the web app lives here (Turkish). Code references keys through t('key').
// Placeholders use {name}. To add another language, copy this file and switch the import in core/i18n.js.
export const strings = {
  'app.name': 'FoodRescue',
  'footer.text': 'FoodRescue - arta kalan gıdayı ihtiyaç sahiplerine ve barınaklara ulaştıran dayanışma platformu. Okul projesi, yerel test sürümü.',

  'common.loading': 'Yükleniyor...',
  'common.back': 'Geri',
  'common.cancel': 'Vazgeç',
  'common.confirm': 'Onayla',
  'common.close': 'Kapat',
  'common.saved': 'Kaydedildi.',

  'error.generic': 'Beklenmeyen bir hata oluştu (kod {status}).',
  'error.network': 'Sunucuya ulaşılamadı. Bağlantınızı kontrol edin.',
  'error.forbidden': 'Bu sayfayı görüntülemek için yetkiniz yok.',
  'error.notFound': 'Sayfa bulunamadı.',

  'nav.label': 'Ana menü',
  'nav.menu': 'Menüyü aç',
  'nav.home': 'Ana sayfa',
  'nav.foods': 'Bağışlar',
  'nav.myFoods': 'İlanlarım',
  'nav.wallet': 'Rezervasyonlarım',
  'nav.desk': 'Teslim masası',
  'nav.admin': 'Yönetim',
  'nav.login': 'Giriş yap',
  'nav.register': 'Kayıt ol',
  'nav.logout': 'Çıkış yap',
  'module.identity': 'Kimlik',

  'role.DONOR': 'Bağışçı işletme',
  'role.BENEFICIARY': 'Yararlanıcı',
  'role.SHELTER': 'Hayvan barınağı',
  'role.ADMIN': 'Yönetici',

  'category.HUMAN': 'İnsan tüketimi',
  'category.ANIMAL': 'Hayvan barınağı',
  'storage.HOT': 'Sıcak',
  'storage.COLD': 'Soğuk',
  'storage.ROOM': 'Oda sıcaklığı',
  'food.status.AVAILABLE': 'Yayında',
  'food.status.EXPIRED': 'Süresi doldu',
  'food.status.CANCELLED': 'İptal edildi',
  'reservation.status.PENDING': 'Bekliyor',
  'reservation.status.COLLECTED': 'Teslim edildi',
  'reservation.status.CANCELLED': 'İptal',
  'reservation.status.EXPIRED': 'Süresi doldu',
  'account.status.ACTIVE': 'Aktif',
  'account.status.PENDING_REVIEW': 'Onay bekliyor',
  'account.status.REJECTED': 'Reddedildi',
  'account.status.SUSPENDED': 'Askıda',
  'account.notActive': 'Hesabınız henüz aktif değil.',
  'complaint.status.OPEN': 'Açık',
  'complaint.status.RESOLVED': 'Haklı bulundu',
  'complaint.status.DISMISSED': 'Reddedildi',

  'format.meters': '{n} m',
  'format.km': '{n} km',
  'format.expired': 'süresi doldu',
  'format.hoursMinutes': '{h} sa {m} dk',
  'format.minutes': '{m} dk',

  'map.unavailable': 'Harita yüklenemedi (internet bağlantısı gerekir). Liste kullanılabilir durumda.',
  'map.noGeolocation': 'Tarayıcınız konum özelliğini desteklemiyor.',
  'map.geolocationDenied': 'Konum izni verilmedi.',

  'auth.login.title': 'Giriş yap',
  'auth.login.submit': 'Giriş yap',
  'auth.login.noAccount': 'Hesabın yok mu?',
  'auth.login.register': 'Kayıt ol',
  'auth.email': 'E-posta',
  'auth.password': 'Şifre',
  'auth.passwordHint': 'En az 8 karakter.',
  'auth.fullName': 'Ad soyad',
  'auth.phone': 'Telefon (isteğe bağlı)',
  'auth.organization': 'İşletme / kurum adı',
  'auth.license': 'Ruhsat / belge no',
  'auth.licenseHint': 'Yönetici bu bilgiyi inceleyerek hesabınızı onaylar.',
  'auth.address': 'Adres',
  'auth.register.title': 'Aramıza katıl',
  'auth.register.chooseRole': 'Nasıl katılmak istersin?',
  'auth.register.haveAccount': 'Zaten hesabın var mı?',
  'auth.register.roleHint.BENEFICIARY': 'Askıda yemekten faydalan. Hesabın hemen aktif olur.',
  'auth.register.roleHint.DONOR': 'Restoran, fırın, yemekhane: arta kalan gıdayı paylaş. Yönetici onayı gerekir.',
  'auth.register.roleHint.SHELTER': 'Hayvan barınağı veya yetiştirici: mutfak artıklarını al. Yönetici onayı gerekir.',
  'auth.register.submit': 'Kayıt ol',
  'auth.register.location': 'İşletme konumu',
  'auth.register.pickLocation': 'Haritaya tıklayarak işletmenizin konumunu seçin.',
  'auth.register.locationSet': 'Seçilen konum: {lat}, {lon}',
  'auth.register.locationRequired': 'Lütfen haritadan işletme konumunu seçin.',
  'auth.register.useMyLocation': 'Konumumu kullan',
  'auth.register.reviewNotice': 'Başvurunuz yönetici tarafından incelenir. Onaya kadar giriş yapabilir ancak ilan açamaz veya rezervasyon yapamazsınız.',
  'auth.register.pending': 'Başvurunuz alındı. Onaylandığında bildirim alacaksınız.',
  'auth.register.welcome': 'Hoş geldiniz.',

  'home.hero.title': 'Çöpe gidecek yemek, birinin sofrasına ulaşsın.',
  'home.hero.subtitle': 'İşletmeler arta kalan hijyenik gıdayı paylaşır; ihtiyaç sahipleri ve hayvan barınakları QR kodla yerinden teslim alır. Kurye yok, ek maliyet yok.',
  'home.cta.browse': 'Bağışları gör',
  'home.cta.join': 'Katıl',
  'home.cta.panel': 'Panelime git',
  'home.stats.rescued': 'Kurtarılan porsiyon',
  'home.stats.pickups': 'Tamamlanan teslim',
  'home.stats.donors': 'Onaylı işletme',
  'home.stats.available': 'Şu an müsait ilan',
  'home.goals.title': 'Amacımız',
  'home.goals.waste.title': 'Sıfır gıda israfı',
  'home.goals.waste.text': 'Gün sonunda atılacak tüketilebilir yemek paylaşıma açılır.',
  'home.goals.dignity.title': 'Onurlu dayanışma',
  'home.goals.dignity.text': 'Yararlanıcıdan belge veya açıklama istenmez; işletme yalnızca rezervasyon kodunu görür.',
  'home.goals.animals.title': 'Can dostlarımıza mama',
  'home.goals.animals.text': 'İnsan tüketimine uygun olmayan artıklar barınaklara ayrılır.',
  'home.goals.pickup.title': 'Sıfır lojistik maliyeti',
  'home.goals.pickup.text': 'Yemek yerinde bekler; yararlanıcı QR kodla gelip teslim alır.',
  'home.how.title': 'Nasıl çalışır?',
  'home.how.donor.title': 'İşletme ilan açar',
  'home.how.donor.text': 'Porsiyon sayısı, saklama koşulu ve son teslim saati girilir. Hijyen beyanı onaylanır.',
  'home.how.receiver.title': 'Yararlanıcı rezerve eder',
  'home.how.receiver.text': 'Harita veya listeden yakın bir ilan seçilir; süreli bir QR kod ve 6 haneli PIN üretilir.',
  'home.how.pickup.title': 'Yerinden teslim',
  'home.how.pickup.text': 'İşletme kodu okutur, teslim kaydedilir ve kurtarılan porsiyon sayacı güncellenir.',
  'home.live.title': 'Canlı bağışlar',
  'home.live.all': 'Tümünü gör',

  'feed.title': 'Bağışlar',
  'feed.subtitle': 'Giriş yapmadan göz atabilirsiniz. Rezervasyon için hesap gerekir.',
  'feed.search': 'Ara: çorba, ekmek...',
  'feed.all': 'Tümü',
  'feed.nearMe': 'Yakınımda',
  'feed.radius': 'Mesafe',
  'feed.radiusOption': '{n} km içinde',
  'feed.count': '{n} ilan',
  'feed.empty': 'Şu anda kriterlere uyan ilan yok.',
  'food.portionsLeft': '{n} porsiyon kaldı',
  'food.until': 'Son teslim {time} ({left})',

  'food.detail.donor': 'İşletme',
  'food.detail.stock': 'Stok',
  'food.detail.stockValue': '{left} / {total} porsiyon',
  'food.detail.until': 'Son teslim',
  'food.detail.storage': 'Saklama',
  'food.detail.address': 'Adres',
  'food.detail.howItWorks': 'Teslim nasıl olur?',
  'food.detail.step1': 'Porsiyonu rezerve edin; QR kod ve PIN oluşur.',
  'food.detail.step2': 'Süre dolmadan işletmeye gidin.',
  'food.detail.step3': 'QR kodu veya PIN kodunu işletme görevlisine gösterin.',
  'food.detail.reserveTitle': 'Rezervasyon',
  'food.detail.unavailable': 'Bu ilan artık müsait değil.',
  'food.detail.loginRequired': 'Rezervasyon için giriş yapmanız gerekir.',
  'food.detail.notReceiver': 'Yalnızca yararlanıcı ve barınak hesapları rezervasyon yapabilir.',
  'food.detail.wrongCategory.BENEFICIARY': 'Bu ilan hayvan barınakları içindir.',
  'food.detail.wrongCategory.SHELTER': 'Bu ilan insan tüketimi içindir.',
  'food.detail.portions': 'Porsiyon sayısı',
  'food.detail.maxPerPerson': 'Kişi başı en fazla {n} porsiyon.',
  'food.detail.reserve': 'Rezerve et',
  'food.detail.reserved': 'Rezervasyon oluşturuldu. Kodunuz hazır.',
  'food.detail.directions': 'Yol tarifi',

  'wallet.title': 'Rezervasyonlarım',
  'wallet.active': 'Aktif rezervasyonlar',
  'wallet.showCode': 'Teslim alırken QR kodu veya PIN kodunu işletme görevlisine gösterin.',
  'wallet.qrAlt': 'Teslim QR kodu',
  'wallet.pin': 'PIN',
  'wallet.portions': '{n} porsiyon',
  'wallet.timeLeft': 'Kalan süre:',
  'wallet.cancel': 'İptal et',
  'wallet.cancelConfirm': '"{title}" rezervasyonunu iptal etmek istiyor musunuz?',
  'wallet.cancelled': 'Rezervasyon iptal edildi.',
  'wallet.empty': 'Aktif rezervasyonunuz yok.',
  'wallet.browse': 'Bağışlara göz at',
  'wallet.history': 'Geçmiş',
  'wallet.complain': 'Sorun bildir',

  'complaint.title': 'Sorun bildir: {title}',
  'complaint.intro': 'Yemek bozuk, eksik veya tarif edilenden farklıysa bize bildirin. Farklı kişilerden gelen şikâyetler işletmenin askıya alınmasına yol açabilir.',
  'complaint.reason': 'Ne oldu?',
  'complaint.placeholder': 'En az 10 karakter...',
  'complaint.submit': 'Gönder',
  'complaint.sent': 'Bildiriminiz alındı. Teşekkürler.',

  'donor.title': 'Panel: {name}',
  'donor.new': 'Yeni ilan',
  'donor.pending': 'İşletmeniz henüz onaylanmadı. Onaylandığında ilan açabileceksiniz ve bildirim alacaksınız.',
  'donor.stats.rescued': 'Kurtarılan porsiyon',
  'donor.stats.pickups': 'Tamamlanan teslim',
  'donor.stats.waiting': 'Bekleyen porsiyon',
  'donor.stats.published': 'Yayınlanan ilan',
  'donor.foods.title': 'İlanlarım',
  'donor.foods.empty': 'Henüz ilan açmadınız.',
  'donor.foods.stock': '{left} / {total} porsiyon',
  'donor.foods.photo': 'Fotoğraf',
  'donor.foods.cancel': 'İlanı kaldır',
  'donor.foods.cancelConfirm': '"{title}" ilanını kaldırmak istiyor musunuz? Bekleyen rezervasyonlar iptal edilir.',
  'donor.form.title': 'Yeni ilan',
  'donor.form.name': 'Başlık',
  'donor.form.description': 'Açıklama (isteğe bağlı)',
  'donor.form.category': 'Kategori',
  'donor.form.storage': 'Saklama koşulu',
  'donor.form.portions': 'Toplam porsiyon',
  'donor.form.maxPerPerson': 'Kişi başı en fazla',
  'donor.form.maxPerPersonHint': 'Adil dağıtım için.',
  'donor.form.until': 'Son teslim zamanı',
  'donor.form.untilHint': 'En fazla 24 saat sonrası.',
  'donor.form.photo': 'Fotoğraf (isteğe bağlı)',
  'donor.form.location': 'Teslim noktası kayıtlı adresiniz: {address}',
  'donor.form.hygiene': 'Gıdanın hijyenik koşullarda saklandığını ve tüketime uygun olduğunu beyan ederim.',
  'donor.form.submit': 'Yayınla',
  'donor.form.published': 'İlan yayınlandı.',

  'desk.title': 'Teslim masası',
  'desk.subtitle': 'Yararlanıcının QR kodunu okutun veya PIN kodunu girin.',
  'desk.code': 'PIN veya kod',
  'desk.codeHint': '6 haneli PIN ya da QR içeriği.',
  'desk.placeholder': '123456',
  'desk.verify': 'Teslimi onayla',
  'desk.success': 'Teslim onaylandı',
  'desk.successDetail': '{title}: {n} porsiyon, {name}',
  'desk.camera.start': 'Kamerayı aç',
  'desk.camera.stop': 'Kamerayı kapat',
  'desk.scanner.unavailable': 'QR okuyucu yüklenemedi. PIN kodunu elle girebilirsiniz.',
  'desk.scanner.denied': 'Kamera açılamadı veya izin verilmedi. PIN kodunu elle girebilirsiniz.',
  'desk.waiting': 'Teslim bekleyenler',
  'desk.noneWaiting': 'Bekleyen rezervasyon yok.',
  'desk.recent': 'Son işlemler',

  'notifications.title': 'Bildirimler',
  'notifications.empty': 'Bildiriminiz yok.',
  'notifications.readAll': 'Tümünü okundu yap',

  'admin.title': 'Yönetim',
  'admin.tab.overview': 'Genel bakış',
  'admin.tab.accounts': 'Başvurular',
  'admin.tab.complaints': 'Şikâyetler',
  'admin.tab.audit': 'Denetim kaydı',
  'admin.overview.pending': 'Onay bekleyen hesap',
  'admin.overview.complaints': 'Açık şikâyet',
  'admin.overview.rescued': 'Kurtarılan porsiyon',
  'admin.overview.available': 'Müsait ilan',
  'admin.overview.users': 'Kullanıcılar',
  'admin.overview.reservations': 'Rezervasyonlar',
  'admin.accounts.empty': 'Bu durumda hesap yok.',
  'admin.accounts.approve': 'Onayla',
  'admin.accounts.reject': 'Reddet',
  'admin.accounts.suspend': 'Askıya al',
  'admin.accounts.reinstate': 'Aktifleştir',
  'admin.accounts.reinstateConfirm': '"{name}" hesabı yeniden aktifleştirilsin mi?',
  'admin.accounts.note': 'Not',
  'admin.accounts.reason': 'Gerekçe',
  'admin.complaints.empty': 'Şikâyet yok.',
  'admin.complaints.resolve': 'Haklı bul',
  'admin.complaints.dismiss': 'Reddet',
  'admin.audit.empty': 'Kayıt yok.',
  'admin.audit.system': 'sistem',
  'admin.audit.col.time': 'Zaman',
  'admin.audit.col.actor': 'Kullanıcı',
  'admin.audit.col.action': 'İşlem',
  'admin.audit.col.entity': 'Kayıt',
  'admin.audit.col.detail': 'Ayrıntı',
};
